// Aliased in wrangler.toml to the worker generated by `vite build`, so the
// type checker never wades into the generated bundle.
declare module 'sveltekit-worker' {
	const worker: ExportedHandler<Env>;
	export default worker;
}
